FROM centos:latest
MAINTAINER attybee10@yahoo.com	

RUN yum update -y
RUN yum install -y httpd net tools

RUN echo "This is a custom inded file built during docker image creation to test" > /var/www/html/index.html

ENTRYPOINT apachectl "-DFOREGROUND"
